document.querySelector(".settings-box .toggle-settings .fa-gear").onclick=function(){this.classList.toggle("fa-spin"),document.querySelector(".settings-box").classList.toggle("open")};const colorsLi=document.querySelectorAll(".colors-list li");colorsLi.forEach(t=>{t.addEventListener("click",t=>{document.documentElement.style.setProperty("--cl",t.target.dataset.color),localStorage.setItem("color_option",t.target.dataset.color),t.target.parentElement.querySelectorAll(".active").forEach(t=>{t.classList.remove("active")}),t.target.classList.add("active")})});let mainColor=localStorage.getItem("color");null!==mainColor&&document.documentElement.style.setProperty("--cl2",localStorage.getItem("color"));const colorLi=document.querySelectorAll(".colors-list li");colorLi.forEach(t=>{t.addEventListener("click",t=>{document.documentElement.style.setProperty("--cl2",t.target.dataset.colors),localStorage.setItem("color",t.target.dataset.colors)})});let mainColors=localStorage.getItem("color_option");null!==mainColors&&(document.documentElement.style.setProperty("--cl",localStorage.getItem("color_option")),document.querySelectorAll(".colors-list li").forEach(t=>{t.classList.remove("active"),t.dataset.color===mainColors&&t.classList.add("active")})),document.querySelector(".toggle-settings .res").onclick=function(){localStorage.clear(),window.location.reload()};
var toc_config = {containerId:'sitemap1', showNew:0, sortAlphabetically:{thePanel:true, theList:true}, activePanel:1, slideSpeed:{down:400, up:400}, slideEasing:{down: null, up: null}, slideCallback:{down:function(){}, up:function(){}}, clickCallback:function(){}, jsonCallback:'sitemap1',delayLoading: 0};
window.onload = function(){!function(e,o){var t=o.getElementById(toc_config.containerId),c=o.getElementsByTagName("head")[0],n=[];e[toc_config.jsonCallback]=function(e){for(var o,c,i=e.feed.entry,a=e.feed.category,l="",s=0,d=a.length;d>s;++s)n.push(a[s].term);for(var r=0,f=i.length;f>r;++r)(toc_config.showNew||toc_config.showNew>0)&&r<toc_config.showNew+1&&(i[r].title.$t+=" %new%");i=toc_config.sortAlphabetically.theList?i.sort(function(e,o){return e.title.$t.localeCompare(o.title.$t)}):i,toc_config.sortAlphabetically.thePanel&&n.sort();for(var g=0,h=n.length;h>g;++g){l+='<div class=\"judul\">'+n[g]+'</div>',l+='<div class=\"konten\"><ol>';for(var _=0,p=i.length;p>_;++_){o=i[_].title.$t;for(var w=0,u=i[_].link.length;u>w;++w)if("alternate"==i[_].link[w].rel){c=i[_].link[w].href;break}for(var v=0,m=i[_].category.length;m>v;++v)n[g]==i[_].category[v].term&&(l+='<li><a href=\"'+c+'\" title=\"'+o.replace(/ \%new\%$/,"")+'\">'+o.replace(/ \%new\%$/,"")+'</a></li>')}l+='</ol></div>'}t.innerHTML=l,"undefined"!=typeof jQuery&&($("#"+toc_config.containerId+" .konten").hide(),$("#"+toc_config.containerId+" .judul").click(function(){$(this).hasClass("aktif")||(toc_config.clickCallback(this),$("#"+toc_config.containerId+" .judul").removeClass("aktif").next().slideUp(toc_config.slideSpeed.up,toc_config.slideEasing.up,toc_config.slideCallback.up),$(this).addClass("aktif").next().slideDown(toc_config.slideSpeed.down,toc_config.slideEasing.down,toc_config.slideCallback.down))}).eq(toc_config.activePanel-1).addClass("aktif").next().slideDown(toc_config.slideSpeed.down,toc_config.slideEasing.down,toc_config.slideCallback.down))};var i=o.createElement("script");i.src="/feeds/posts/summary?alt=json-in-script&max-results=9999&callback="+toc_config.jsonCallback,"onload"==toc_config.delayLoading?e.onload=function(){c.appendChild(i)}:e.setTimeout(function(){c.appendChild(i)},toc_config.delayLoading)}(window,document);};
"true"==hideColorBox&&$(document).ready(function(){$(".settings-box").css("display","none")});
if (window.location.hostname != "www.blogger.com"){$.ajax({dataType: "json",url: "https://www.blogger.com/feeds/5085293420862991854/pages/default/6620083549136527089?alt=json-in-script",method: "GET",dataType: "jsonp",success: function(e) {var o, t = $(e.entry.content.$t),n = t.find("li"),a = t.find("script"),l = [];$allow = !0, $("body").append(a);for (o = 0; o < n.length; o += 1) l.push($(n[o]).text());o = window.location.hostname.toLowerCase(), n = window.location.href.toLowerCase();var s;l.length;for (s = 0; s < l.length; s += 1) {if (-1 != o.indexOf(l[s])) {break}s == l.length - 1 && $('body *').remove() && $('body').addClass('PhoneTechnique-Demo').append("<style>body.PhoneTechnique-Demo {background:url(https://1.bp.blogspot.com/-AchJGofwvJc/YOkMEsX7owI/AAAAAAAABas/8-DWU-j760QzlvH9nh06IKbnqEeKmiWtgCLcBGAsYHQ/s0/PhoneTechniqueCopyRight.webp) no-repeat center #eee!important;background-position: center center;height: 98vh;overflow: hidden;}</style>")}}});}
!function(){for(var a=/(\[img\])?((http:|https:)?\/\/\S*?\.(jpg|gif|png|bmp|jpeg]))(\[\/img\])?/gi,b=/(\[vid\])?http(?:s?):\/\/(?:www\.)?youtu(?:be\.com\/watch\?v=|\.be\/)([\w\-\_]*)(&(amp;)?‌?[\w\?‌?=]*)?(\[\/vid\])?/gi,c=/(\[vid\])?(http:|https:)?\/\/(vimeo.com)\/([0-9]*)(\[\/vid\])?/gi,d=document.querySelectorAll(".comment-content"),e=0;e<d.length;e++){for(var f=d[e].getElementsByTagName("a"),g=0;g<f.length;g++)if(f[g].href.match(a)||f[g].href.match(b)||f[g].href.match(c)){var h=document.createElement("span");h.innerHTML=f[g].href;var i=f[g];i.parentNode.insertBefore(h,i),f[g].href="",f[g].innerHTML=""}var j=d[e].innerHTML;j=j.replace(a,'<img style="max-width: 100%; height: auto;display: blocK;margin: 10px auto;" src="$2"" alt=""/>'),j=j.replace(b,'<div style="position:relative;width:100%;height:0;padding-bottom:56.25%;overflow:hidden;margin:20px auto;"><iframe style="position: absolute;width: 100%;height: 100%;top: 0;left: 0;" src="https://www.youtube.com/embed/$2" frameborder="0" allowfullscreen></iframe></div>'),j=j.replace(c,'<div style="position:relative;width:100%;height:0;padding-bottom:56.25%;overflow:hidden;margin:20px auto;"><iframe style="position: absolute;width: 100%;height: 100%;top: 0;left: 0;" src="https://player.vimeo.com/video/$4" frameborder="0" allowfullscreen></iframe></div>'),d[e].innerHTML=j}}();
let darkMode = localStorage.getItem('darkMode'); 
const darkModeToggle = document.querySelector("#zToggleMode");
const enableDarkMode = () => {document.body.classList.add('dark');localStorage.setItem('darkMode', 'enabled');}
const disableDarkMode = () => {document.body.classList.remove("dark");localStorage.setItem("darkMode", null);}
if (darkMode === "enabled") {enableDarkMode();}
darkModeToggle.addEventListener('click', () => {
darkMode = localStorage.getItem('darkMode'); 
if (darkMode !== 'enabled') {enableDarkMode();} else {  disableDarkMode(); }});
let rdMode = localStorage.getItem('rdMode'); 
const rdModeToggle = document.querySelector("#rd");
const enableRdMode = () => {document.body.classList.add('rd');localStorage.setItem('rdMode', 'enabled');}
const disableRdMode = () => {document.body.classList.remove("rd");localStorage.setItem("rdMode", null);}
if (rdMode === "enabled") {enableRdMode();}
rdModeToggle.addEventListener('click', () => {
rdMode = localStorage.getItem('rdMode'); 
if (rdMode !== 'enabled') {enableRdMode();} else {  disableRdMode(); }});
let boxMode = localStorage.getItem('boxMode'); 
const boxModeToggle = document.querySelector("#box");
const enableBoxMode = () => {document.body.classList.add('box');localStorage.setItem('boxMode', 'enabled');}
const disableBoxMode = () => {document.body.classList.remove("box");localStorage.setItem("boxMode", null);}
if (boxMode === "enabled") {enableBoxMode();}
boxModeToggle.addEventListener('click', () => {
boxMode = localStorage.getItem('boxMode'); 
if (boxMode !== 'enabled') {enableBoxMode();} else {  disableBoxMode(); }});
